// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ5Z7BHNV2LelpCWiyRYu2XkJqPpRuwh0',
    appId: '1:96041562673:web:458f9e8e472ecba8dddb10',
    messagingSenderId: '96041562673',
    projectId: 'to-do-fe803',
    authDomain: 'to-do-fe803.firebaseapp.com',
    storageBucket: 'to-do-fe803.appspot.com',
    measurementId: 'G-KQZXBW20L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMhP227izwxm_1Kj18PGF2QnAvV8RAPAs',
    appId: '1:96041562673:android:16de468854db9af8dddb10',
    messagingSenderId: '96041562673',
    projectId: 'to-do-fe803',
    storageBucket: 'to-do-fe803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGNd5IYp0L877ShhKTvQiafOA6QWwtAU',
    appId: '1:96041562673:ios:186d3ab2772a2cdedddb10',
    messagingSenderId: '96041562673',
    projectId: 'to-do-fe803',
    storageBucket: 'to-do-fe803.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCGNd5IYp0L877ShhKTvQiafOA6QWwtAU',
    appId: '1:96041562673:ios:186d3ab2772a2cdedddb10',
    messagingSenderId: '96041562673',
    projectId: 'to-do-fe803',
    storageBucket: 'to-do-fe803.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ5Z7BHNV2LelpCWiyRYu2XkJqPpRuwh0',
    appId: '1:96041562673:web:133716a569d37716dddb10',
    messagingSenderId: '96041562673',
    projectId: 'to-do-fe803',
    authDomain: 'to-do-fe803.firebaseapp.com',
    storageBucket: 'to-do-fe803.appspot.com',
    measurementId: 'G-1TQ4FWMPY2',
  );
}
